name: Task
description: Create a new task for backlog tracking
title: "[task]: "
labels: []
assignees: []
type: task

body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - feature
        - fix
        - chore
        - docs
        - refactor
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the task
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
       label: What is the objective.

  - type: checkboxes
    id: checklist
    attributes:
      label: Changes required
      options:
        - label: API
        - label: Database
        - label: UI Flow
        - label: Dependencies
        
